// One active partner: hiring changes real movement, preparation and decision priorities.
export const STAFF = Object.freeze({
  helper: {
    name: '見習いのハル',
    icon: '🐣',
    role: 'allrounder',
    description: '切る・盛る担当。煮る・焼くはあなた。',
    capabilities: ['prep', 'serve'],
    canDash: false,
    cost: 0,
    decisionMs: 1800,
    speed: 1,
    chop: 1,
    cook: 1,
  },
  runner: {
    name: '配膳係のソラ',
    icon: '⚡',
    role: 'runner',
    description: '運搬と盛り付け専門。足が速い。',
    capabilities: ['serve'],
    canDash: false,
    cost: 80,
    decisionMs: 1400,
    speed: 1.18,
    chop: 1.15,
    cook: 1,
  },
  chef: {
    name: '料理人のナギ',
    icon: '🔪',
    role: 'chef',
    description: '仕込みと加熱専門。配膳はしない。',
    capabilities: ['prep', 'cook'],
    canDash: false,
    cost: 180,
    decisionMs: 900,
    speed: 0.9,
    chop: 0.55,
    cook: 0.75,
  },
  sous: {
    name: '副料理長のリン',
    icon: '⏱️',
    role: 'expediter',
    description: '全工程に対応。締切を優先。',
    capabilities: ['prep', 'cook', 'serve'],
    canDash: false,
    cost: 260,
    decisionMs: 500,
    speed: 1.05,
    chop: 0.8,
    cook: 0.9,
  },
  prep: {
    name: '仕込み係のミオ',
    icon: '🥬',
    role: 'chef',
    description: '切る専門。手際がいい。',
    capabilities: ['prep'],
    canDash: false,
    cost: 60,
    decisionMs: 2000,
    speed: 1,
    chop: 0.55,
    cook: 1,
  },
  sprinter: {
    name: '特急配膳のレオ',
    icon: '💨',
    role: 'runner',
    description: '配膳専門。ダッシュで届ける。',
    capabilities: ['serve'],
    canDash: true,
    cost: 200,
    decisionMs: 1200,
    speed: 1.2,
    chop: 1,
    cook: 1,
  },
  veteran: {
    name: '店長候補のアオ',
    icon: '🌟',
    role: 'expediter',
    description: '全工程に対応。ダッシュもできる。',
    capabilities: ['prep', 'cook', 'serve'],
    canDash: true,
    cost: 420,
    decisionMs: 300,
    speed: 1.15,
    chop: 0.75,
    cook: 0.8,
  },
});
